### PR TITLE
✨ add docs

### PR DESCRIPTION
**Pull request by AntoineKM**
- [x] Fix https://github.com/tonightpass/kitchen/pull/55#issuecomment-1337120082
- [x] Add theme support (require #58)
- [x] Improve playground with good loaders (require #25)
- [x] Set Space Grotesk and Space Mono by default (require #20)

### CODE REVIEW

**Review by jerembdn — APPROVED** [review]

**Comment by jerembdn** [comment]
The theme loader is not in page height 
image

**Review by YounesBessa — APPROVED** [review]

**Review by YounesBessa — APPROVED** [review]

**Review by YounesBessa — APPROVED** [review]

**Comment by AntoineKM** [comment]
Im in troubles with https://github.com/googlefonts/spacemono/issues/4 and ligatures

**Comment by AntoineKM** [comment]
image

**Comment by AntoineKM** [comment]
Well, without wasting any more time we are going to deploy this, because several issues are more or less simple to realize this one has been dispatched in several issues, please pay attention.

**Pull request merged**
