### PR TITLE
📝 add colors and sizes of theme

### PR DESCRIPTION
**Pull request by jerembdn**

### CODE REVIEW

**Review by AntoineKM — CHANGES_REQUESTED** [review]
Everything will be explained in the theme Builder about this with all the sizes, weights, colors etc, so I don't think it is relevant. Otherwise the color page is fine but it could be greatly improved like here:
https://vercel.com/design/color
or here 
https://chakra-ui.com/docs/styled-system/theme
with boxes that show the color plus it lacks all the colors that concern the layout... everything you have indicated is mostly focused on the text colors maybe you should review the text.mdx page

**Comment by AntoineKM** [comment]
I could have told you before you gave your time to do this if you had made an issue before starting your PR but no matter, you can either close this one or add improvements!

**Comment by jerembdn** [comment]
It makes me 2 minutes to do it so there's not a problem, the fact that i have links on the icon documentation that includes colors and accents and i wanted to do a color and accent documentation

**Comment by jerembdn** [comment]
Then we can think about how to document our colors and accents and the way that the developer can make his own theme etc.

**Comment by AntoineKM** [comment]
@jerembdn is this pr done ? so we can merge it ?

**Pull request closed without merging**
